server:
  port: 8080
  servlet:
    contextPath:  /api


info:
  app:
    description: '@project.description@'
    encoding: '@project.build.sourceEncoding@'
    java: '@java.version@'
    name: '@project.name@'
    version: '@project.version@'
